init:
  # If there's a tag, use that as the version.
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq "true"){Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"}
restore_script:
  - cmd: dotnet restore 
test_script:
  - cmd: dotnet build 
  - cmd: dotnet test 
on_success:
  - ps: .\coverage.ps1 -UploadCodecov
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
os: Visual Studio 2019
artifacts:
- path: '**\*.nupkg'
  name: messaging-nuget-packages