name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  release:
    env:
      BRANCH: release-test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/r')
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
    - name: Get version
      run: echo "::set-env name=VERSION::${GITHUB_REF//refs\/tags\/r/}"
    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@master
      with:
        version: ${{ env.VERSION }}
    - name: Set projects version 
      uses: hawthorne-abendsen/dotnet-version-tool@master
      with:
        version: ${{ env.VERSION }}
    - name: Get changelog entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v1.1.0
      with:
        version: ${{ env.VERSION }}
        path: ./CHANGELOG.md
    - name: Remove trigger tag
      run: git push --delete origin "r$VERSION"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build release
      run: |
        dotnet build -c Release
        dotnet publish Centaurus.Alpha -r win-x64 -c Release /p:PublishSingleFile=true -o Release/win-x64 /p:DebugType=None
        dotnet publish Centaurus.Auditor -r win-x64 -c Release /p:PublishSingleFile=true -o Release/win-x64 /p:DebugType=None
        dotnet publish Centaurus.Alpha -r linux-x64 -c Release /p:PublishSingleFile=true -o Release/linux-x64 /p:DebugType=None
        dotnet publish Centaurus.Auditor -r linux-x64 -c Release /p:PublishSingleFile=true -o Release/linux-x64 /p:DebugType=None
        dotnet publish Centaurus.Alpha -r osx-x64 -c Release /p:PublishSingleFile=true -o Release/osx-x64 /p:DebugType=None
        dotnet publish Centaurus.Auditor -r osx-x64 -c Release /p:PublishSingleFile=true -o Release/osx-x64 /p:DebugType=None
    - name: Release
      run: |
        cd Release
        set -x
        assets=()
        for dir in *
        do 
          f="${dir%/}.zip" 
          zip -r $f $dir
          assets+=("-a" "$f")
        done 
        hub release create "${assets[@]}" -m "Release v$VERSION" -m "${{steps.changelog_reader.outputs.log_entry}}" "v$VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Amend changes
      run: | 
        git add -A
        git commit --amend --no-edit
        git push -f origin ${{env.BRANCH}}
        
